<?php

namespace Vorkfork\Database;

use Doctrine\ORM\EntityManager;

class CustomEntityManager extends EntityManager
{
	/**
	 * @param $className
	 * @param $id
	 * @param $lockMode
	 * @param $lockVersion
	 * @return $this|null
	 * @throws \Doctrine\ORM\Exception\ORMException
	 * @throws \Doctrine\ORM\OptimisticLockException
	 * @throws \Doctrine\ORM\TransactionRequiredException
	 */
	public function find($className, $id, $lockMode = null, $lockVersion = null): ?Entity
	{
		return parent::find($className, $id, $lockMode, $lockVersion); // TODO: Change the autogenerated stub
	}

}